### ISSUE TITLE
Issue with S3 Sink parquet format using PyFlink

### ISSUE THREAD

**Issue by davidshtian** [aws-samples/amazon-kinesis-data-analytics-java-examples#8]
I've tested the Python example in [amazon-kinesis-data-analytics-java-examples/blob/master/python/S3Sink/streaming-file-sink.py](https://github.com/aws-samples/amazon-kinesis-data-analytics-java-examples/blob/master/python/S3Sink/streaming-file-sink.py) and when using the default csv format, the job run normally. However, when changing it to parquet, the job failed.

Is there any extra settings to configure S3 Sink using parquet format? Thanks~

**Comment by davidshtian** [comment]
I've tried downloaded [flink-sql-parquet_2.11-1.11.2.jar](https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-parquet_2.11/1.11.2/flink-sql-parquet_2.11-1.11.2.jar) and combine with amazon-kinesis-sql-connector-flink-2.0.3.jar, but the job still failed.

**Comment by ibuda** [comment]
Are there ny updates on this, as I'm experiencing the same problems? @davidshtian did you manage to find a solution on your own?

**Comment by davidshtian** [comment]
> Are there ny updates on this, as I'm experiencing the same problems? @davidshtian did you manage to find a solution on your own?

Yes, you could find the solution here: https://github.com/aws-samples/amazon-kinesis-data-analytics-java-examples/issues/4
